steps:

# Build Meeds version.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/meeds:latest', '.']

  # Add more tags
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/meeds:latest']

# store images
images: 
- 'gcr.io/$PROJECT_ID/meeds:latest'
