version: '2'
services:
  web:
    image: nginx:1.14-alpine
    expose:
      - "80"
    ports: 
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - meeds
  meeds:
    image: meeds-io/meeds
    environment:
      MEEDS_PROXY_VHOST: localhost
      MEEDS_PROXY_PORT: 80
      MEEDS_DB_HOST: mysql
      MEEDS_PROXY_SSL: "false"
      MEEDS_DB_TYPE: mysql
      MEEDS_DB_NAME: meeds
      MEEDS_DB_USER: meeds
      MEEDS_DB_PASSWORD: my-secret-pw
      MEEDS_ADDONS_LIST: 
      MEEDS_JVM_LOG_GC_ENABLED: "true"
    volumes:
      - meeds_data:/srv/meeds
      - meeds_logs:/var/log/meeds
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-super-secret-pw
      MYSQL_DATABASE: meeds
      MYSQL_USER: meeds
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  meeds_data:
  meeds_logs:
  mysql_data:
